version: "3"
services:
  user-db:
    image: postgres:16
    container_name: user-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata/user:/var/lib/postgresql/data

  booking-db:
    image: postgres:16
    container_name: booking-db
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata/booking:/var/lib/postgresql/data

  notification-db:
    image: postgres:16
    container_name: notification-db
    environment:
      POSTGRES_DB: notif_db
      POSTGRES_USER: notifier
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata/notification:/var/lib/postgresql/data

  frontend:
    build: ./services/frontend
    container_name: coworking-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://host.docker.internal:8000
    restart: unless-stopped